name: 'Ubuntu Build and Test'
description: 'Builds and tests a Swift package on Ubuntu'

runs:
  using: "composite"
  steps:
    - name: Get Swift and OS versions
      shell: bash
      run: |
        SWIFT_VERSION=$(swift --version | head -n 1 | cut -d ' ' -f 4 | cut -d'-' -f1)
        OS_VERSION=$(. /etc/os-release && echo $VERSION_CODENAME)
        echo "SWIFT_VERSION=$SWIFT_VERSION" >> $GITHUB_ENV
        echo "OS_VERSION=$OS_VERSION" >> $GITHUB_ENV

    - name: Cache swift package modules
      uses: actions/cache@v4
      with:
        path: .build
        key: spm-${{ env.OS_VERSION }}-${{ env.SWIFT_VERSION }}-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          spm-${{ env.OS_VERSION }}-${{ env.SWIFT_VERSION }}-

    - name: Build
      shell: bash
      run: swift build

    - name: Run tests
      shell: bash
      run: swift test --enable-test-discovery --enable-code-coverage 