public enum DeviceTypeID : String {
  case AppleTV1080p = "AppleTV-1080p"
  case AppleTV4K1080p = "Apple-TV-4K-1080p"
  case AppleTV4K2ndgeneration1080p = "Apple-TV-4K-2nd-generation-1080p"
  case AppleTV4K2ndgeneration4K = "Apple-TV-4K-2nd-generation-4K"
  case AppleTV4K3rdgeneration1080p = "Apple-TV-4K-3rd-generation-1080p"
  case AppleTV4K3rdgeneration4K = "Apple-TV-4K-3rd-generation-4K"
  case AppleTV4K4K = "Apple-TV-4K-4K"
  case AppleVisionPro = "Apple-Vision-Pro"
  case AppleWatchSE40mm = "Apple-Watch-SE-40mm"
  case AppleWatchSE40mm2ndgeneration = "Apple-Watch-SE-40mm-2nd-generation"
  case AppleWatchSE44mm = "Apple-Watch-SE-44mm"
  case AppleWatchSE44mm2ndgeneration = "Apple-Watch-SE-44mm-2nd-generation"
  case AppleWatchSeries338mm = "Apple-Watch-Series-3-38mm"
  case AppleWatchSeries342mm = "Apple-Watch-Series-3-42mm"
  case AppleWatchSeries440mm = "Apple-Watch-Series-4-40mm"
  case AppleWatchSeries444mm = "Apple-Watch-Series-4-44mm"
  case AppleWatchSeries540mm = "Apple-Watch-Series-5-40mm"
  case AppleWatchSeries544mm = "Apple-Watch-Series-5-44mm"
  case AppleWatchSeries640mm = "Apple-Watch-Series-6-40mm"
  case AppleWatchSeries644mm = "Apple-Watch-Series-6-44mm"
  case AppleWatchSeries741mm = "Apple-Watch-Series-7-41mm"
  case AppleWatchSeries745mm = "Apple-Watch-Series-7-45mm"
  case AppleWatchSeries841mm = "Apple-Watch-Series-8-41mm"
  case AppleWatchSeries845mm = "Apple-Watch-Series-8-45mm"
  case AppleWatchSeries941mm = "Apple-Watch-Series-9-41mm"
  case AppleWatchSeries945mm = "Apple-Watch-Series-9-45mm"
  case AppleWatchUltra249mm = "Apple-Watch-Ultra-2-49mm"
  case AppleWatchUltra49mm = "Apple-Watch-Ultra-49mm"
  case iPad5thgeneration = "iPad--5th-generation-"
  case iPad6thgeneration = "iPad--6th-generation-"
  case iPad7thgeneration = "iPad--7th-generation-"
  case iPad8thgeneration = "iPad--8th-generation-"
  case iPad10thgeneration = "iPad-10th-generation"
  case iPad9thgeneration = "iPad-9th-generation"
  case iPadAir3rdgeneration = "iPad-Air--3rd-generation-"
  case iPadAir4thgeneration = "iPad-Air--4th-generation-"
  case iPadAir2 = "iPad-Air-2"
  case iPadAir5thgeneration = "iPad-Air-5th-generation"
  case iPadPro = "iPad-Pro"
  case iPadPro105inch = "iPad-Pro--10-5-inch-"
  case iPadPro11inch = "iPad-Pro--11-inch-"
  case iPadPro11inch2ndgeneration = "iPad-Pro--11-inch---2nd-generation-"
  case iPadPro129inch2ndgeneration = "iPad-Pro--12-9-inch---2nd-generation-"
  case iPadPro129inch3rdgeneration = "iPad-Pro--12-9-inch---3rd-generation-"
  case iPadPro129inch4thgeneration = "iPad-Pro--12-9-inch---4th-generation-"
  case iPadPro97inch = "iPad-Pro--9-7-inch-"
  case iPadPro11inch3rdgeneration = "iPad-Pro-11-inch-3rd-generation"
  case iPadPro11inch4thgeneration16GB = "iPad-Pro-11-inch-4th-generation-16GB"
  case iPadPro11inch4thgeneration8GB = "iPad-Pro-11-inch-4th-generation-8GB"
  case iPadPro129inch5thgeneration = "iPad-Pro-12-9-inch-5th-generation"
  case iPadPro129inch6thgeneration16GB = "iPad-Pro-12-9-inch-6th-generation-16GB"
  case iPadPro129inch6thgeneration8GB = "iPad-Pro-12-9-inch-6th-generation-8GB"
  case iPadmini5thgeneration = "iPad-mini--5th-generation-"
  case iPadmini4 = "iPad-mini-4"
  case iPadmini6thgeneration = "iPad-mini-6th-generation"
  case iPhone11 = "iPhone-11"
  case iPhone11Pro = "iPhone-11-Pro"
  case iPhone11ProMax = "iPhone-11-Pro-Max"
  case iPhone12 = "iPhone-12"
  case iPhone12Pro = "iPhone-12-Pro"
  case iPhone12ProMax = "iPhone-12-Pro-Max"
  case iPhone12mini = "iPhone-12-mini"
  case iPhone13 = "iPhone-13"
  case iPhone13Pro = "iPhone-13-Pro"
  case iPhone13ProMax = "iPhone-13-Pro-Max"
  case iPhone13mini = "iPhone-13-mini"
  case iPhone14 = "iPhone-14"
  case iPhone14Plus = "iPhone-14-Plus"
  case iPhone14Pro = "iPhone-14-Pro"
  case iPhone14ProMax = "iPhone-14-Pro-Max"
  case iPhone15 = "iPhone-15"
  case iPhone15Plus = "iPhone-15-Plus"
  case iPhone15Pro = "iPhone-15-Pro"
  case iPhone15ProMax = "iPhone-15-Pro-Max"
  case iPhone6s = "iPhone-6s"
  case iPhone6sPlus = "iPhone-6s-Plus"
  case iPhone7 = "iPhone-7"
  case iPhone7Plus = "iPhone-7-Plus"
  case iPhone8 = "iPhone-8"
  case iPhone8Plus = "iPhone-8-Plus"
  case iPhoneSE = "iPhone-SE"
  case iPhoneSE2ndgeneration = "iPhone-SE--2nd-generation-"
  case iPhoneSE3rdgeneration = "iPhone-SE-3rd-generation"
  case iPhoneX = "iPhone-X"
  case iPhoneXR = "iPhone-XR"
  case iPhoneXS = "iPhone-XS"
  case iPhoneXSMax = "iPhone-XS-Max"
  case iPodtouch7thgeneration = "iPod-touch--7th-generation-"
}
//SimRuntime.iOS-15-5
//SimRuntime.iOS-16-0
//SimRuntime.iOS-17-2
//SimRuntime.iOS-17-4
//SimRuntime.tvOS-17-4
//SimRuntime.watchOS-10-0
//SimRuntime.watchOS-10-2
//SimRuntime.watchOS-10-4
//SimRuntime.watchOS-8-5
//SimRuntime.watchOS-9-0
//SimRuntime.watchOS-9-4
//SimRuntime.xrOS-1-1
