name: 'macOS Build and Test'
description: 'Builds and tests a Swift package on macOS'

inputs:
  type:
    description: 'Build type (ios, watchos, visionos, tvos)'
    required: false
  xcode:
    description: 'Xcode version path'
    required: true
  deviceName:
    description: 'Simulator device name'
    required: false
  osVersion:
    description: 'Simulator OS version'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set Xcode Name
      shell: bash
      run: echo "XCODE_NAME=$(basename -- ${{ inputs.xcode }} | sed 's/\.[^.]*$//' | cut -d'_' -f2)" >> $GITHUB_ENV
    
    - name: Setup Xcode
      shell: bash
      run: sudo xcode-select -s ${{ inputs.xcode }}/Contents/Developer
  
    - name: Set SDK and Platform
      if: inputs.type
      shell: bash
      run: |
        case ${{ inputs.type }} in
          ios)
            echo "PLATFORM=iOS Simulator" >> $GITHUB_ENV
            echo "SDK=iphonesimulator" >> $GITHUB_ENV
            ;;
          watchos)
            echo "PLATFORM=watchOS Simulator" >> $GITHUB_ENV
            echo "SDK=watchsimulator" >> $GITHUB_ENV
            ;;
          visionos)
            echo "PLATFORM=visionOS Simulator" >> $GITHUB_ENV
            echo "SDK=xrsimulator" >> $GITHUB_ENV
            ;;
          tvos)
            echo "PLATFORM=tvOS Simulator" >> $GITHUB_ENV
            echo "SDK=appletvsimulator" >> $GITHUB_ENV
            ;;
        esac

    - uses: irgaly/xcode-cache@v1
      if: inputs.type
      with:
        key: xcode-${{ runner.os }}-${{ env.XCODE_NAME }}-${{ hashFiles('Package.resolved') }}-${{ github.sha }}
        restore-keys: |
          xcode-${{ runner.os }}-${{ env.XCODE_NAME }}-${{ hashFiles('Package.resolved') }}-                        
          xcode-${{ runner.os }}-${{ env.XCODE_NAME }}-          

    - name: Cache swift package modules
      if: ${{ !inputs.type }}
      uses: actions/cache@v4
      with:
        path: .build
        key: spm-${{ runner.os }}-${{ env.XCODE_NAME }}-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          spm-${{ runner.os }}-${{ env.XCODE_NAME }}-

    - name: Build SPM
      if: ${{ !inputs.type }}
      shell: bash
      run: swift build

    - name: Run Swift Package tests
      if: ${{ !inputs.type }}
      shell: bash
      run: swift test -v --enable-code-coverage

    - name: Run Device Tests
      if: inputs.type
      shell: bash
      run: >
        xcodebuild test
        -scheme SimulatorServices
        -sdk ${{ env.SDK }}
        -destination 'platform=${{ env.PLATFORM }},name=${{ inputs.deviceName }},OS=${{ inputs.osVersion }}'
        -enableCodeCoverage YES
